			<div>
			
			<h2>Create Teams</h2>
			
			<div class="fix-left" style="margin: 0 168px 0 53px; width: 367px;">
			<h5>Team A</h5>
	
	
			<form method="post" action="<?php  echo $this->baseUrl(); ?>">
			 <div style="float: left; width: 182px;">
			 <div style="font-family: 'Russo One',sans-serif; font-size: 18px; margin: 0 0 0 0px;">Gamer Tag:</div> 
			  <input type='text' name='a[name][]' />
			 </div>
			 
			 <div style="float: left;">
			 <div style="font-family: 'Russo One',sans-serif; font-size: 18px; margin: 0 0 0 0px;">Phone #:</div> 
			  <input type='text' name='a[number][]' />
			 </div>
			 
			
			</div>
			 
			<div class="fix-left-a" style="width: 350px;">
			<h5>Team B</h5>
			
			 <div style="float: left; width: 182px;">
			 <div style="font-family: 'Russo One',sans-serif; font-size: 18px; margin: 0 0 0 0px;">Gamer Tag:</div> 
			 <input type='text' name='b[name][]' />
			 </div>
			 
			 <div style="float: left;">
			 <div style="font-family: 'Russo One',sans-serif; font-size: 18px; margin: 0 0 0 0px;">Phone #:</div> 
			 <input type='text' name='b[number][]' />
			 </div>
			
			
			</div>
			
			<center><input type="image" style="margin: 40px 0 0 0;" src="<?php  echo $this->baseUrl(); ?>/images/create-teams.jpg" ALT="SUBMIT!"></center>
			
			</form>
			
			
			</div>