
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="en-US" xml:lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
	<head>
	
			<title>QRag - QR Code Tag</title>
	
	<link rel="stylesheet" type="text/css" href="<?php  echo $this->baseUrl(); ?>/css/style.css" />
		
		<link href='http://fonts.googleapis.com/css?family=Russo+One' rel='stylesheet' type='text/css'>
		
	</head>

	<body>

		 <div id="main">
			<div id="head">

				<div id="logo">
					<a href="<?php echo  $this->baseUrl();?>"><img src="<?php  echo $this->baseUrl(); ?>/images/logo.png" border="0" width="348" height="107" /></a>
				</div>
				
			</div> <!-- HEAD end -->

			<div id="nav">

				<ul>
				<li><a href="<?php  echo $this->baseUrl(); ?>/index/about"><img src="<?php  echo $this->baseUrl(); ?>/images/about.jpg" /></a></li>
				<li><a href="<?php  echo $this->baseUrl(); ?>/index/rules"><img src="<?php  echo $this->baseUrl(); ?>/images/rules.jpg" /></a></li>
				<li><a href="<?php  echo $this->baseUrl(); ?>/index/upgrade"><img src="<?php  echo $this->baseUrl(); ?>/images/upgrade.jpg" /></a></li>
				</ul> 
				
			</div>
			
			<div class="clearfix"></div>
			
			
<?php echo $this->layout()->content; ?>
			
			
			
			<div class="clearfix"></div>
			
			</div>

</body>
</html>